name: rakhsa
description: "Rakhsa"

publish_to: 'none'

version: 1.2.1+13

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  awesome_notifications: ^0.9.3+1
  barcode_widget: ^2.0.4
  cached_network_image: ^3.2.3
  camera: ^0.10.0+1
  carousel_slider: ^5.0.0
  circular_countdown_timer: ^0.2.3
  connectivity_plus: ^3.0.0
  cunning_document_scanner: ^1.2.3
  cupertino_icons: ^1.0.6
  currency_text_input_formatter: ^2.1.10
  dartz: ^0.10.1
  date_count_down: ^3.0.0
  device_info_plus: ^10.1.2
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_gemini: ^3.0.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.3
  flutter_otp_text_field: ^1.2.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_typeahead: ^4.3.7
  flutter_widget_from_html: ^0.15.3
  fluttercontactpicker: ^4.7.0
  gallery_saver_plus: ^3.1.1
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  get_it: ^7.6.7
  google_api_headers: ^2.0.0
  google_maps_flutter: ^2.4.0
  google_mlkit_face_detection: ^0.11.0
  google_sign_in: ^6.0.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  intl: ^0.19.0
  lecle_flutter_absolute_path: ^0.0.2+1
  local_auth: ^2.3.0
  location: ^6.0.2
  modal_progress_hud_nsn: ^0.5.1
  multi_image_picker_plus: ^0.0.4
  new_version_plus: ^0.0.10
  permission_handler: ^11.3.1
  provider: ^6.1.2
  readmore: ^2.2.0
  shared_preferences: ^2.2.2
  shimmer: ^2.0.0
  slide_countdown: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  socket_io_client: ^3.0.2
  soundpool: ^2.3.0
  table_calendar: ^3.1.2
  tflite_flutter: ^0.11.0
  timelines: ^0.1.0
  tuple: ^2.0.1
  uuid: ^4.5.1
  video_compress: ^3.1.3
  weather: ^3.1.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/weather/
    - assets/images/update/
    - assets/sounds/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
